import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm, SubmitHandler } from "react-hook-form";

import { api } from "@/utils/api";
import { RouterOutputs } from "@/utils/api";
import { getSession } from "next-auth/react";
// import { DynamicFormData, formSchema } from "@/models/Form";
import { generateDynamicFormSchema } from "@/models/Form";
import { GetServerSidePropsContext } from "next";
import { db } from "@/server/db";
import TextInput from "@/components/form/TextInput";
import { z } from "zod";
import EmailInput from "./EmailInput";
import CheckboxInput from "./CheckboxInput";
import RadioInput from "./RadioInput";
import DropdownInput from "./DropdownInput";
import DateInput from "./DateInput";
import TimeInput from "./TimeInput";
import FileInput from "./FileInput";

interface FormPageProps {
  formData: RouterOutputs["form"]["getFormData"];
}

export default function Form({ formData }: FormPageProps) {
  type FormInputs = Record<string, string | string[] | FileList>;
  const dynamicFormSchema = generateDynamicFormSchema(formData?.items ?? []);

  const {
    register,
    handleSubmit,
    trigger,
    reset,
    getFieldState,
    getValues,
    formState: { errors, isValid, isLoading: isFormLoading },
  } = useForm<z.infer<typeof dynamicFormSchema>>({
    reValidateMode: "onBlur",
    resolver: zodResolver(dynamicFormSchema),
  });

  const onSubmit: SubmitHandler<FormInputs> = (data) => {
    console.log("data", data);
    reset();
  };

  console.log("errors", errors);

  return (
    <>
      <Head>
        <title>Form</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col items-center bg-slate-200">
        <>
          {/* <button
            onClick={() => trigger()}
            className="mb-2 rounded bg-gray-300 p-2 text-xl"
          >
            Display Data Requirements
          </button> */}
          <form
            onSubmit={handleSubmit(onSubmit)}
            className="mt-8 flex min-w-[50%] flex-col"
          >
            <header className="mb-16 w-full bg-white shadow-sm">
              <div className="px-4 py-4">
                <h1 className="text-lg font-semibold leading-6 text-gray-900">
                  {formData?.name}
                </h1>
              </div>
            </header>

            {formData?.items.map((item, index) => {
              switch (item.type) {
                case "TEXT":
                  return (
                    <div className="mb-12 w-full rounded bg-white shadow-sm">
                      <div className="px-4 py-4">
                        <TextInput
                          key={item.id}
                          id={item.id}
                          index={index}
                          text={item.text}
                          register={register}
                          errors={errors}
                        />
                      </div>
                    </div>
                  );
                case "EMAIL":
                  return (
                    <div className="mb-12 w-full rounded bg-white shadow-sm">
                      <div className="px-4 py-4">
                        <EmailInput
                          id={item.id}
                          index={index}
                          text={item.text}
                          register={register}
                          errors={errors}
                        />
                      </div>
                    </div>
                  );
                case "CHECKBOX":
                  return (
                    <div className="mb-12 w-full rounded bg-white shadow-sm">
                      <div className="px-4 py-4">
                        <CheckboxInput
                          id={item.id}
                          index={index}
                          text={item.text}
                          options={item.options}
                          register={register}
                          errors={errors}
                        />
                      </div>
                    </div>
                  );

                case "RADIO":
                  return (
                    <div className="mb-12 w-full rounded bg-white shadow-sm">
                      <div className="px-4 py-4">
                        <RadioInput
                          id={item.id}
                          index={index}
                          text={item.text}
                          options={item.options}
                          register={register}
                          errors={errors}
                        />
                      </div>
                    </div>
                  );
                case "DROPDOWN":
                  return (
                    <div className="mb-12 w-full rounded bg-white shadow-sm">
                      <div className="px-4 py-4">
                        <DropdownInput
                          id={item.id}
                          index={index}
                          text={item.text}
                          options={item.options}
                          register={register}
                          errors={errors}
                        />
                      </div>
                    </div>
                  );
                case "FILE":
                  return (
                    <div className="mb-12 w-full rounded bg-white shadow-sm">
                      <div className="px-4 py-4">
                        <FileInput
                          id={item.id}
                          index={index}
                          text={item.text}
                          register={register}
                          errors={errors}
                        />
                      </div>
                    </div>
                  );
                case "DATE":
                  return (
                    <div className="mb-12 w-full rounded bg-white shadow-sm">
                      <div className="px-4 py-4">
                        <DateInput
                          id={item.id}
                          index={index}
                          text={item.text}
                          register={register}
                          errors={errors}
                        />
                      </div>
                    </div>
                  );
                case "TIME":
                  return (
                    <div className="mb-12 w-full rounded bg-white shadow-sm">
                      <div className="px-4 py-4">
                        <TimeInput
                          id={item.id}
                          index={index}
                          text={item.text}
                          register={register}
                          errors={errors}
                        />
                      </div>
                    </div>
                  );
                default:
                  return null;
              }
            })}

            <div className="mb-12 w-full">
              <div className="flex justify-between">
                <button
                  type="reset"
                  className="rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
                >
                  Reset
                </button>
                <button
                  type="submit"
                  className="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                >
                  Submit
                </button>
              </div>
            </div>
          </form>
        </>
      </main>
    </>
  );
}
