import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";

export default function FormPage() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Form</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-slate-200">
        <div className="mt-8 flex min-w-[60%] flex-col">
          <header className="mb-20 w-full bg-white shadow-sm">
            <div className="px-4 py-4">
              <h1 className="text-lg font-semibold leading-6 text-gray-900">
                Dashboard
              </h1>
            </div>
          </header>
          <div className="mb-12 w-full rounded bg-white shadow-sm">
            <div className="px-4 py-4">
              <label
                htmlFor="email"
                className="text-md block font-medium leading-6 text-gray-900"
              >
                Email
              </label>
              <div className="mt-2">
                <input
                  type="email"
                  name="email"
                  id="email"
                  className="block w-full rounded-md border-0 px-1 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                  placeholder="you@example.com"
                />
              </div>
            </div>
          </div>
          <div className="mb-12 w-full rounded bg-white shadow-sm">
            <div className="px-4 py-4">
              <h1 className="text-lg font-semibold leading-6 text-gray-900">
                Dashboard
              </h1>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
